# Generated by Django 4.0.5 on 2022-08-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Res', '0003_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='compeleted',
            field=models.BooleanField(default=False),
        ),
    ]
