# Generated by Django 4.0.5 on 2022-08-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Res', '0005_todolist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
