# Generated by Django 4.0.5 on 2022-08-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Res', '0006_alter_todolist_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='orders',
            field=models.OneToOneField(default=25, on_delete=django.db.models.deletion.CASCADE, to='Res.orders'),
            preserve_default=False,
        ),
    ]
