# Generated by Django 4.0.5 on 2022-08-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Res', '0007_reservation_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='orders',
        ),
    ]
