# Generated by Django 4.0.5 on 2022-08-30 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Res', '0008_remove_reservation_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UserOrders',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userorders', to='Res.orders'),
        ),
    ]
