# Generated by Django 4.0.5 on 2022-08-30 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Res', '0009_user_userorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserOrders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userorders', to='Res.orders'),
        ),
    ]
