# Generated by Django 4.0.5 on 2022-08-30 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Res', '0010_alter_user_userorders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserOrders',
        ),
    ]
