# Generated by Django 4.1.1 on 2022-09-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Res', '0013_remove_user_userorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Reservation_time',
            field=models.DateTimeField(max_length=200),
        ),
    ]
